[package]
name = "tlisp"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = """
Lisp interpreter in Rust
"""

[[bin]]
name = "tlisp"
path = "src/main.rs"

[dependencies]
linefeed = "0.6.0"
